### ISSUE TITLE
Linux setup instructions

### ISSUE THREAD

**Issue by sanamon** [MichaelRColton/PSDR#10]
Hi,
Trying to setup the build environment for ubuntu 14.04.
Got eclipse installed including the addons. Checked out the project. 
But when trying to build, i get an error saying "fatal error: cstdlib: No such file or directory	_cxx.cpp	/PSDR/system/src/newlib	line 13	C/C++ Problem"

Is there some other prereq that i've missed, or something else?  Newbie to eclipse and to cross-compilation so any tips/ideas welcome!

Cheers, Jonas

**Comment by pwarren** [comment]
Hi Jonas,

in PR #5, there's a commit to fix that: af4d1fa94eeb1e4b0ad401f3e1b09837f69a9066. Michael has not merged that into the project yet, and it may well break compilation with other toolchains.

It's a simple fix though, in Source/system/src/newlib/_cxx.cpp change the line
```#include <cstilb>```
to be
```#include <stdlib.h>```

And you should be good to go!

**Comment by sanamon** [comment]
Thanks Paul!

I changed the line in _cxx.cpp from <cstdlib> to <stdlib.h>
but now the linker fails instead:

/usr/lib/gcc/arm-none-eabi/4.8.2/../../../arm-none-eabi/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status

08:36:03 Build Finished (took 47s.892ms)

I'm sure it's just me who cant use the eclipse system...
Regards,
Jonas

**Comment by sanamon** [comment]
I figured it out myself. It seems that for ubuntu 14.04 the **gcc-arm-none-eabi** package doesnt include the libstdc++ lib. A [known but unfixed](https://bugs.launchpad.net/ubuntu/+source/gcc-arm-none-eabi/+bug/1293024) bug apparently.

Fixed by manually downloading http://de.archive.ubuntu.com/ubuntu/pool/universe/libs/libstdc++-arm-none-eabi/libstdc++-arm-none-eabi-newlib_4.9.3+svn227297-1+8_all.deb and installing.

Now builds!

**Comment by sanamon** [comment]
marked as closed

**Comment by sanamon** [comment]
Update: could not build the project anyway. Had to de-install gcc-arm-none-eabi package and instead install gcc-arm-embedded following the instructions here: [link](https://launchpad.net/~team-gcc-arm-embedded/+archive/ubuntu/ppa)
